apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-fedodo-be-activitypub
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: fedodo-be-activitypub
  template:
    metadata:
      labels:
        app: fedodo-be-activitypub
    spec:
      containers:
        - name: fedodo
          image: {{quote .Values.microservices.fedodo_be_activitypub.version}}
          imagePullPolicy: Always
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: port-http
          env:
            - name: VERSION
              value:  {{ .Chart.AppVersion }}
            - name: DOMAINNAME
              value: {{ .Values.domainName }}
            - name: MONGO_HOSTNAME
              value: "cluster0.mnp03hj.mongodb.net"
            - name: MONGO_USERNAME
              value: "root"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fedodo-secrets
                  key: mongodb-password
