apiVersion: v1
kind: Service
metadata:
  name: service-fedodo-be-activitypub
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: fedodo-be-activitypub
  ports:
    - port: 80
      targetPort: port-http
      name: http