name: "fedodo"
namespace: "fedodo"
domainName: "fedodo.social"

# DO NOT INCLUDE THIS BLOCK IN YOUR values.yaml
microservices:
  fedodo_be_auth:
    version: "fedodo/fedodo.be.auth:13"
  fedodo_be_activitypub:
    version: "fedodo/fedodo.be.activitypub:138"
