name: "fedodo"
namespace: "fedodo"
domainName: "fedodo.social"

microservices:
  fedodo_be_auth:
    version: "" # Only for debugging purposes! Do not use this option!
  fedodo_be_activitypub:
    version: "" # Only for debugging purposes! Do not use this option!
