name: "fedodo"
namespace: "fedodo"
domainName: "fedodo.social"

# DO NOT INCLUDE THIS BLOCK IN YOUR values.yaml
microservices:
  fedodo_be_auth:
    version: "fedodo/fedodo.be.auth:20"
  fedodo_be_activitypub:
    version: "fedodo/fedodo.be.activitypub:147"
  fedodo_ui_micro:
    version: "fedodo/fedodo.ui.micro:9"
  fedodo_ui_home:
    version: "fedodo/fedodo.ui.home:2"