apiVersion: v1
kind: Service
metadata:
  name: service-fedodo.be.auth
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: fedodo.be.auth
  ports:
    - port: 80
      targetPort: port-http
      name: http