apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-fedodo-ui-home
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: fedodo-ui-home
  template:
    metadata:
      labels:
        app: fedodo-ui-home
    spec:
      containers:
        - name: fedodo
          image: {{ .Values.microservices.fedodo_ui_home.version }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: "20Mi"
              cpu: "20m"
          ports:
            - containerPort: 80
              name: port-http
          env:
            - name: CONFIG
              value: {{ .Values.microservices.fedodo_ui_home.config }}
            - name: MICRO_DISABLED
              value: {{ quote .Values.microservices.fedodo_ui_micro.disabled }} # This needs to be quote because it is not a string
