apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-fedodo-ui-home
spec:
  entrypoints:
    - web
    - websecure
  routes:
    - match: Headers(`X-ROUTE`,`nginx`)
      kind: Rule
      services:
        - name: service-fedodo-ui-home
          port: 80

{{/*---*/}}

{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: ingress-fedodo-ui-home*/}}
{{/*  namespace: {{ .Values.namespace }}*/}}
{{/*  annotations:*/}}
{{/*    cert-manager.io/cluster-issuer: letsencrypt*/}}
{{/*    traefik.ingress.kubernetes.io/router.entrypoints: websecure*/}}
{{/*    traefik.ingress.kubernetes.io/router.middlewares: default-redirectscheme@kubernetescrd*/}}
{{/*spec:*/}}
{{/*  tls:*/}}
{{/*    - hosts:*/}}
{{/*        - home.{{ .Values.domainName }}*/}}
{{/*      secretName: home-{{ .Values.name }}-cert*/}}
{{/*  rules:*/}}
{{/*    - host: home.{{ .Values.domainName }}*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          - path: /*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: service-fedodo-ui-home*/}}
{{/*                port:*/}}
{{/*                  number: 80*/}}

{{/*---*/}}
{{/*# Needed because of HTTP to HTTPS redirecting*/}}
{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: ingress-fedodo.ui.home-http*/}}
{{/*  namespace: {{ .Values.namespace }}*/}}
{{/*  annotations:*/}}
{{/*    traefik.ingress.kubernetes.io/router.entrypoints: web*/}}
{{/*    traefik.ingress.kubernetes.io/router.middlewares: default-redirectscheme@kubernetescrd*/}}
{{/*spec:*/}}
{{/*  rules:*/}}
{{/*    - host: home.{{ .Values.domainName }}*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          - path: /*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: service-fedodo-ui-home*/}}
{{/*                port:*/}}
{{/*                  number: 80*/}}

{{/*---*/}}
{{/*apiVersion: traefik.containo.us/v1alpha1*/}}
{{/*kind: Middleware*/}}
{{/*metadata:*/}}
{{/*  name: redirectscheme*/}}
{{/*  namespace: {{ .Values.namespace }}*/}}
{{/*spec:*/}}
{{/*  redirectRegex:*/}}
{{/*    regex: '^https?://(?:www\.)?(.+)'*/}}
{{/*    replacement: "https://${1}"*/}}
{{/*    permanent: true*/}}