apiVersion: v1
kind: Service
metadata:
  name: service-fedodo-ui-home
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: fedodo-ui-home
  ports:
    - port: 80
      targetPort: port-http
      name: http