{{ if not .Values.microservices.fedodo_ui_micro.disabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-fedodo-ui-micro
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: fedodo-ui-micro
  template:
    metadata:
      labels:
        app: fedodo-ui-micro
    spec:
      containers:
        - name: fedodo
          image: {{ quote .Values.microservices.fedodo_ui_micro.version }}
          imagePullPolicy: Always
          resources:
            requests: 
              memory: {{ .Values.microservices.fedodo_ui_micro.requests.memory }}
              cpu: {{ .Values.microservices.fedodo_ui_micro.requests.cpu }}
            limits:
              memory: {{ .Values.microservices.fedodo_ui_micro.limits.memory }}
              cpu: {{ .Values.microservices.fedodo_ui_micro.limits.cpu }}
          ports:
            - containerPort: 80
              name: port-http

{{ end }}