{{ if not .Values.microservices.fedodo_ui_micro.disabled }}

apiVersion: v1
kind: Service
metadata:
  name: service-fedodo-ui-micro
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: fedodo-ui-micro
  ports:
    - port: 80
      targetPort: port-http
      name: http

{{ end }}