apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedodo-deployment
  namespace: dev-fedodo
spec:
  selector:
    matchLabels:
      app: fedodo
  template:
    metadata:
      labels:
        app: fedodo
    spec:
      containers:
        - name: fedodo
          image: fedodo/fedodo.server:dev_32
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 80
              name: port-http
          env:
            - name: DOMAINNAME
              value: "dev.fedodo.social"
            - name: MONGO_HOSTNAME
              value: "cluster0.mnp03hj.mongodb.net"
            - name: MONGO_USERNAME
              value: "root"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fedodo-secrets
                  key: mongodb-password
            - name: API_ENCRYPTION_CERT
              valueFrom:
                secretKeyRef:
                  name: fedodo-certs
                  key: fedodo-encryption
            - name: API_SIGNING_CERT
              valueFrom:
                secretKeyRef:
                  name: fedodo-certs
                  key: fedodo-signing