name: Release Chart

on:
  workflow_dispatch:

  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: "fedodo"

jobs:
  ReleaseVersion:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Publish
      - name: Push Helm Chart to DockerHub
        uses: bsord/helm-push@v4.1.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          access-token: ${{ secrets.DOCKERHUB_TOKEN }}
          registry-url: 'oci://registry-1.docker.io/${{ env.DOCKERHUB_USERNAME }}'
          force: true
          chart-folder: .
          useOCIRegistry: true
