name: Release Chart

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: "fedodo"

jobs:
  ReleaseVersion:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Build
      - name: Build the Helm Chart
        run: helm package .

      # Publish
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the image to dockerhub
        run: helm push Fedodo.Chart-0.0.1.tgz  oci://registry-1.docker.io/${{ env.DOCKERHUB_USERNAME }}
